### ISSUE TITLE
Failed to load resource: the server responded with a status of 406 (Not Acceptable)

### ISSUE THREAD

**Issue by tilleryd** [ozone-development/ozp-iwc-integrationDemo#1]
I was receiving 406 errors on all template files.

```Failed to load resource: the server responded with a status of 406 (Not Acceptable)```

I fixed the problem by adding the following line in index.js

```
acceptable.push('text/html');
```

I would love to help by creating a Pull Request but just wanted to see what the feedback is first.

Thanks.

**Comment by arw180** [comment]
Thanks for the report. Our primary IWC developer is on vacation until late next week, but I'll pass this along to him for when he gets back.

**Comment by tilleryd** [comment]
FYI subsequent setups of the Vagrant dev box worked ok.

**Comment by Kevin-K** [comment]
Sorry for the delayed response, an example integration of the IWC was added to the [ozp-iwc repository itself](https://github.com/ozone-development/ozp-iwc#demo). This includes a NeDB backend to do Data.api persistence as well as a backend for the System.api's application listings for applications in the [ozp-demo repository](https://github.com/ozone-development/ozp-demo). We'll gladly take the PR for the 406 fix on the templates, but further development on the integration demonstration effort has been merged into the ozp-iwc repo.
